# Generated by Django 5.0.7 on 2024-08-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
