# Generated by Django 5.0.8 on 2024-08-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=255)),
                ('start_day', models.DateField()),
                ('finish_day', models.DateField()),
                ('number_of_task', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('comic_id', models.AutoField(primary_key=True, serialize=False)),
                ('comic_img', models.CharField(max_length=255)),
                ('number_of_panel', models.CharField(max_length=255)),
                ('unlocked', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('panel_id', models.AutoField(primary_key=True, serialize=False)),
                ('comic_panel', models.CharField(max_length=255)),
                ('panel_img', models.CharField(max_length=255)),
                ('unlocked', models.BooleanField(default=False)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comic')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goal')),
            ],
        ),
        migrations.AddField(
            model_name='comic',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task'),
        ),
        migrations.CreateModel(
            name='TaskByAI',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('number_of_task', models.CharField(max_length=255)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goal')),
            ],
        ),
    ]
