# Generated by Django 5.0.8 on 2024-08-13 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=255)),
                ('start_day', models.DateField()),
                ('finish_day', models.DateField()),
                ('number_of_task', models.IntegerField()),
                ('ai_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskByAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('start_day', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.goal')),
            ],
        ),
    ]
